<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Currency extends \AppBundle\Entity\Currency implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'link', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'link_text', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'available', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'price', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'imageFile', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'currencyLink', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'background', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'backgroundFile'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'link', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'link_text', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'available', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'price', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'imageFile', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'currencyLink', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'background', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'backgroundFile'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Currency $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$image]);

        return parent::setImageFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setBackgroundFile(\Symfony\Component\HttpFoundation\File\File $background = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackgroundFile', [$background]);

        return parent::setBackgroundFile($background);
    }

    /**
     * {@inheritDoc}
     */
    public function getBackgroundFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackgroundFile', []);

        return parent::getBackgroundFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setBackground($background)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackground', [$background]);

        return parent::setBackground($background);
    }

    /**
     * {@inheritDoc}
     */
    public function getBackground()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackground', []);

        return parent::getBackground();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink($link)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink', [$link]);

        return parent::setLink($link);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', []);

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkText($linkText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkText', [$linkText]);

        return parent::setLinkText($linkText);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkText', []);

        return parent::getLinkText();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailable($available)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailable', [$available]);

        return parent::setAvailable($available);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailable', []);

        return parent::getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrencyLink($currencyLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrencyLink', [$currencyLink]);

        return parent::setCurrencyLink($currencyLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencyLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencyLink', []);

        return parent::getCurrencyLink();
    }

}
